name: luql_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - astunparse=1.6.3
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - cloudpickle=3.1.1
  - comm=0.2.2
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=9.2.1.18
  - debugpy=1.8.9
  - decorator=5.1.1
  - dm-tree=0.1.8
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - flatbuffers=24.3.25
  - gast=0.6.0
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.62.2
  - h2=4.2.0
  - h5py=3.12.1
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jax=0.4.27
  - jaxlib=0.4.23
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keras=3.8.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libabseil=20240116.2
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=19.1.5
  - libcxxabi=19.1.5
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ml_dtypes=0.3.2
  - namex=0.0.8
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openssl=3.4.0
  - opt-einsum=3.4.0
  - optree=0.14.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - protobuf=4.25.3
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.1.24
  - python-tzdata=2025.1
  - python_abi=3.9
  - pytz=2024.1
  - pyzmq=26.2.0
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - scipy=1.13.1
  - setuptools=75.6.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.46.0
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - tensorflow=2.16.1
  - tensorflow-base=2.16.1
  - tensorflow-estimator=2.16.1
  - tensorflow-probability=0.24.0
  - termcolor=2.5.0
  - tf-keras=2.16.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
